#! /bin/bash

echo "Generating dev environment..."

jq -r '.azurestack.acr_registry_name' .terraform/output.json > $DEVCONTAINER_REGISTRY_NAME
jq -r '.azurestack.docker_image_tag' .terraform/output.json > $DEVCONTAINER_IMAGE_TAG

DEVCONTAINER_KUBECONFIG_PATH=$(pwd)/kubeconfig.yaml 
# this is the default path for the kubeconfig file
# generated by terraform_output_to_kubeconfig.sh script

echo DEVCONTAINER_REGISTRY_NAME="${DEVCONTAINER_REGISTRY_NAME}" > .env.dev
echo DEVCONTAINER_KUBECONFIG_PATH="${DEVCONTAINER_KUBECONFIG_PATH}" >> .env.dev
echo DEVCONTAINER_IMAGE_TAG="${DEVCONTAINER_IMAGE_TAG}" >> .env.dev